export const USERS_RESET = "USERS_RESET";
export const RESET = "RESET";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_LOADING = "GET_ALL_USERS_LOADING";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";

export const GET_ONE_USER_REQUEST = "GET_ONE_USER_REQUEST";
export const GET_ONE_USER_LOADING = "GET_ONE_USER_LOADING";
export const GET_ONE_USER_SUCCESS = "GET_ONE_USER_SUCCESS";
export const GET_ONE_USER_FAILURE = "GET_ONE_USER_FAILURE";

export const UPDATE_ONE_USER_REQUEST = "UPDATE_ONE_USER_REQUEST";
export const UPDATE_ONE_USER_LOADING = "UPDATE_ONE_USER_LOADING";
export const UPDATE_ONE_USER_SUCCESS = "UPDATE_ONE_USER_SUCCESS";
export const UPDATE_ONE_USER_FAILURE = "UPDATE_ONE_USER_FAILURE";

export const FILTER_USERS_REQUEST = "FILTER_USERS_REQUEST";
export const FILTER_USERS_LOADING = "FILTER_USERS_LOADING";
export const FILTER_USERS_SUCCESS = "FILTER_USERS_SUCCESS";
export const FILTER_USERS_FAILURE = "FILTER_USERS_FAILURE";

export const ADD_ONE_USER_REQUEST = "ADD_ONE_USER_REQUEST";
export const ADD_ONE_USER_LOADING = "ADD_ONE_USER_LOADING";
export const ADD_ONE_USER_SUCCESS = "ADD_ONE_USER_SUCCESS";
export const ADD_ONE_USER_FAILURE = "ADD_ONE_USER_FAILURE";

export const GET_USER_DOCUMENTS_REQUEST = "GET_USER_DOCUMENTS_REQUEST";
export const GET_USER_DOCUMENTS_LOADING = "GET_USER_DOCUMENTS_LOADING";
export const GET_USER_DOCUMENTS_SUCCESS = "GET_USER_DOCUMENTS_SUCCESS";
export const GET_USER_DOCUMENTS_FAILURE = "GET_USER_DOCUMENTS_FAILURE";

export const DELETE_ONE_USER_REQUEST = "DELETE_ONE_USER_REQUEST";
export const DELETE_ONE_USER_LOADING = "DELETE_ONE_USER_LOADING";
export const DELETE_ONE_USER_SUCCESS = "DELETE_ONE_USER_SUCCESS";
export const DELETE_ONE_USER_FAILURE = "DELETE_ONE_USER_FAILURE";

export const PROFIL_REQUEST = "PROFIL_REQUEST";
export const PROFIL_LOADING = "PROFIL_LOADING";
export const PROFIL_SUCCESS = "PROFIL_SUCCESS";
export const PROFIL_FAILURE = "PROFIL_FAILURE";

export type ActionTypes =
  | "GET_ALL_USERS_REQUEST"
  | "GET_ALL_USERS_REQUEST"
  | "GET_ALL_USERS_LOADING"
  | "GET_ALL_USERS_SUCCESS"
  | "GET_ALL_USERS_FAILURE"
  | "GET_ONE_USER_REQUEST"
  | "GET_ONE_USER_LOADING"
  | "GET_ONE_USER_SUCCESS"
  | "GET_ONE_USER_FAILURE"
  | "UPDATE_ONE_USER_REQUEST"
  | "UPDATE_ONE_USER_LOADING"
  | "UPDATE_ONE_USER_SUCCESS"
  | "UPDATE_ONE_USER_FAILURE"
  | "FILTER_USERS_REQUEST"
  | "FILTER_USERS_LOADING"
  | "FILTER_USERS_SUCCESS"
  | "FILTER_USERS_FAILURE"
  | "ADD_ONE_USER_REQUEST"
  | "ADD_ONE_USER_LOADING"
  | "ADD_ONE_USER_SUCCESS"
  | "ADD_ONE_USER_FAILURE"
  | "DELETE_ONE_USER_REQUEST"
  | "DELETE_ONE_USER_LOADING"
  | "DELETE_ONE_USER_SUCCESS"
  | "DELETE_ONE_USER_FAILURE"
  | "GET_USER_DOCUMENTS_REQUEST"
  | "GET_USER_DOCUMENTS_LOADING"
  | "GET_USER_DOCUMENTS_SUCCESS"
  | "GET_USER_DOCUMENTS_FAILURE"
  | "PROFIL_REQUEST"
  | "PROFIL_SUCCESS"
  | "PROFIL_FAILURE"
  | "RESET";
