export const COMPANIES_RESET = "COMPANIES_RESET";
export const RESET = "RESET";

export const GET_ALL_COMPANIES_REQUEST = "GET_ALL_COMPANIES_REQUEST";
export const GET_ALL_COMPANIES_LOADING = "GET_ALL_COMPANIES_LOADING";
export const GET_ALL_COMPANIES_SUCCESS = "GET_ALL_COMPANIES_SUCCESS";
export const GET_ALL_COMPANIES_FAILURE = "GET_ALL_COMPANIES_FAILURE";

export const GET_ONE_COMPANY_REQUEST = "GET_ONE_COMPANY_REQUEST";
export const GET_ONE_COMPANY_LOADING = "GET_ONE_COMPANY_LOADING";
export const GET_ONE_COMPANY_SUCCESS = "GET_ONE_COMPANY_SUCCESS";
export const GET_ONE_COMPANY_FAILURE = "GET_ONE_COMPANY_FAILURE";

export const UPDATE_ONE_COMPANY_REQUEST = "UPDATE_ONE_COMPANY_REQUEST";
export const UPDATE_ONE_COMPANY_LOADING = "UPDATE_ONE_COMPANY_LOADING";
export const UPDATE_ONE_COMPANY_SUCCESS = "UPDATE_ONE_COMPANY_SUCCESS";
export const UPDATE_ONE_COMPANY_FAILURE = "UPDATE_ONE_COMPANY_FAILURE";

export const FILTER_COMPANIES_REQUEST = "FILTER_COMPANIES_REQUEST";
export const FILTER_COMPANIES_LOADING = "FILTER_COMPANIES_LOADING";
export const FILTER_COMPANIES_SUCCESS = "FILTER_COMPANIES_SUCCESS";
export const FILTER_COMPANIES_FAILURE = "FILTER_COMPANIES_FAILURE";

export const ADD_ONE_COMPANY_REQUEST = "ADD_ONE_COMPANY_REQUEST";
export const ADD_ONE_COMPANY_LOADING = "ADD_ONE_COMPANY_LOADING";
export const ADD_ONE_COMPANY_SUCCESS = "ADD_ONE_COMPANY_SUCCESS";
export const ADD_ONE_COMPANY_FAILURE = "ADD_ONE_COMPANY_FAILURE";

export const ADD_ONE_COMPANY_ADDRESS_REQUEST = "ADD_ONE_COMPANY_ADDRESS_REQUEST";
export const ADD_ONE_COMPANY_ADDRESS_LOADING = "ADD_ONE_COMPANY_ADDRESS_LOADING";
export const ADD_ONE_COMPANY_ADDRESS_SUCCESS = "ADD_ONE_COMPANY_ADDRESS_SUCCESS";
export const ADD_ONE_COMPANY_ADDRESS_FAILURE = "ADD_ONE_COMPANY_ADDRESS_FAILURE";

export const GET_COMPANY_DOCUMENTS_REQUEST = "GET_COMPANY_DOCUMENTS_REQUEST";
export const GET_COMPANY_DOCUMENTS_LOADING = "GET_COMPANY_DOCUMENTS_LOADING";
export const GET_COMPANY_DOCUMENTS_SUCCESS = "GET_COMPANY_DOCUMENTS_SUCCESS";
export const GET_COMPANY_DOCUMENTS_FAILURE = "GET_COMPANY_DOCUMENTS_FAILURE";

export const DELETE_ONE_COMPANY_REQUEST = "DELETE_ONE_COMPANY_REQUEST";
export const DELETE_ONE_COMPANY_LOADING = "DELETE_ONE_COMPANY_LOADING";
export const DELETE_ONE_COMPANY_SUCCESS = "DELETE_ONE_COMPANY_SUCCESS";
export const DELETE_ONE_COMPANY_FAILURE = "DELETE_ONE_COMPANY_FAILURE";

export type ActionTypes =
  | "GET_ALL_COMPANIES_REQUEST"
  | "GET_ALL_COMPANIES_REQUEST"
  | "GET_ALL_COMPANIES_LOADING"
  | "GET_ALL_COMPANIES_SUCCESS"
  | "GET_ALL_COMPANIES_FAILURE"
  | "GET_ONE_COMPANY_REQUEST"
  | "GET_ONE_COMPANY_LOADING"
  | "GET_ONE_COMPANY_SUCCESS"
  | "GET_ONE_COMPANY_FAILURE"
  | "UPDATE_ONE_COMPANY_REQUEST"
  | "UPDATE_ONE_COMPANY_LOADING"
  | "UPDATE_ONE_COMPANY_SUCCESS"
  | "UPDATE_ONE_COMPANY_FAILURE"
  | "FILTER_COMPANIES_REQUEST"
  | "FILTER_COMPANIES_LOADING"
  | "FILTER_COMPANIES_SUCCESS"
  | "FILTER_COMPANIES_FAILURE"
  | "ADD_ONE_COMPANY_REQUEST"
  | "ADD_ONE_COMPANY_LOADING"
  | "ADD_ONE_COMPANY_SUCCESS"
  | "ADD_ONE_COMPANY_FAILURE"
  | "DELETE_ONE_COMPANY_REQUEST"
  | "DELETE_ONE_COMPANY_LOADING"
  | "DELETE_ONE_COMPANY_SUCCESS"
  | "DELETE_ONE_COMPANY_FAILURE"
  | "GET_COMPANY_DOCUMENTS_REQUEST"
  | "GET_COMPANY_DOCUMENTS_LOADING"
  | "GET_COMPANY_DOCUMENTS_SUCCESS"
  | "GET_COMPANY_DOCUMENTS_FAILURE"
  | "ADD_ONE_COMPANY_ADDRESS_REQUEST"
  | "ADD_ONE_COMPANY_ADDRESS_LOADING"
  | "ADD_ONE_COMPANY_ADDRESS_SUCCESS"
  | "ADD_ONE_COMPANY_ADDRESS_FAILURE"
  | "RESET";
